### ISSUE TITLE
Unable to trace mysql

### ISSUE THREAD

**Issue by Akhilesh-Anb** [elastic/packetbeat#141] opened 2015-05-28 07:01 UTC
I'm getting HTTP requests in packetbeat. but im unable to get from mysql. please help me.

**Comment by tsg** [comment] 2015-05-28 08:21
For troubleshooting requests we would prefer that you open an issue on [discuss](https://discuss.elastic.co/c/beats/packetbeat).

Please also provide more information (version, operating system, mysql version). Also, if you can make a [trace](https://www.elastic.co/guide/en/beats/packetbeat/current/_recording_a_trace.html) that would be the most helpful.

I'm closing this for now because we want to keep Github only for confirmed bugs and enhancements requests.

**Closed by tsg** 2015-05-28 08:21 UTC
Labels: question
