### ISSUE TITLE
-d "*" does not include the "publish" selector

### ISSUE THREAD

**Issue by darxriggs** [elastic/packetbeat#339] opened 2015-10-27 22:54 UTC
When running `./packetbeat -e -c etc/packetbeat.yml -d "*"` no output from publisher is logged.

When running `./packetbeat -e -c etc/packetbeat.yml -d "*,publish"` the output from publisher is logged.

I would expect that `-d "*"` enables debug logging for publisher.

**Comment by urso** [comment] 2015-10-27 23:32
the '*' option should work as it sets a bool being checked before any selectors. Can you provide some console output for comparison?

**Comment by andrewkroh** [comment] 2015-10-27 23:37
I think the cause is that `logp.IsDebug` doesn't handle `*` correctly.

https://github.com/elastic/libbeat/blob/master/publisher/preprocess.go#L61

**Comment by urso** [comment] 2015-10-28 00:14
@andrewkroh you are right. And it's not the only selector being affected.

**Comment by tsg** [comment] 2015-11-02 23:11
Fixed by elastic/libbeat#226.

**Closed by tsg** 2015-11-02 23:11 UTC
Labels: bug
