### ISSUE TITLE
nil Pointer in redis parser

### ISSUE THREAD

**Issue by voelzmo** [elastic/packetbeat#395] opened 2015-11-20 19:38 UTC
This is the stacktrace I'm seeing, not sure how to gather more debug information:

```
2015/11/20 19:36:47.194387 log.go:110: ERR ParseRedis exception. Recovering, but please report this: runtime error: invalid memory address or nil pointer dereference.
2015/11/20 19:36:47.194481 log.go:111: ERR Stacktrace: /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/elastic/libbeat/logp/log.go:111 (0x48bfb6)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x47d72e)
/usr/local/go/src/runtime/panic.go:423 (0x44d329)
/usr/local/go/src/runtime/panic.go:42 (0x44b9e9)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x46228a)
/go/src/github.com/elastic/packetbeat/protos/redis/redis.go:579 (0x51af62)
/go/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:87 (0x5202f3)
/go/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:173 (0x52142d)
/go/src/github.com/elastic/packetbeat/decoder/decoder.go:136 (0x6c6041)
/go/src/github.com/elastic/packetbeat/sniffer/sniffer.go:352 (0x532a09)
/go/src/github.com/elastic/packetbeat/packetbeat.go:212 (0x422f2b)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x47fa71)
```

**Comment by andrewkroh** [comment] 2015-11-20 19:48
Thanks for reporting. Looks like a duplicate of #384.

**Closed** 2015-11-20 19:49 UTC
Labels: duplicate
