### ISSUE TITLE
Agent (v 0.5 and above) does not publish to redis/elasticsearch when running inside docker container

### ISSUE THREAD

**Issue by rshriram** [elastic/packetbeat#145] opened 2015-06-01 13:50 UTC
I wanted to play around with version 0.5 or even 1.0 beta, to see the performance of af_packet. I am running the packetbeat agent inside a docker container. Nginx server is running inside another container on the same host. The packetbeat agent inside the docker container is able to parse http requests but does not publish any transactions to either redis or elasticsearch (tried each individually) running on a remote host. I can verify that publishing transactions worked with version 0.3.3, where the redis server had a "packetbeat" list object with a large number of entries.  

Any idea what could be going wrong? Below is my packetbeat.conf file (for 0.5.0) and packetbeat.yml file (for 1.0.0 Beta), as well as my dockerfile

My Dockerfile:
```
FROM phusion/baseimage:0.9.15
MAINTAINER Tudor Golubenco <tudor@packetbeat.com>

RUN apt-get update
RUN apt-get -y -q install libpcap0.8

RUN curl -L -o /tmp/packetbeat_0.5.0-1_amd64.deb https://github.com/elastic/packetbeat/releases/download/v0.5.0/packetbeat_0.5.0-1_amd64.deb
RUN dpkg -i /tmp/packetbeat_0.5.0-1_amd64.deb
#RUN curl -L -o /tmp/packetbeat_0.3.3-1_amd64.deb https://github.com/packetbeat/packetbeat/releases/download/v0.3.3/packetbeat_0.3.3-1_amd64.deb
#RUN dpkg -i /tmp/packetbeat_0.3.3-1_amd64.deb

# Define mountable directories.
VOLUME ["/etc/packetbeat"]

#ADD packetbeat.conf /etc/packetbeat/packetbeat.conf
```

My packetbeat.conf file:
```
[output]

  [output.elasticsearch]
    enabled = false
    host = "10.11.0.5"
    port = 9200
    save_topology = false

  [output.redis]
    enabled = true
    host = "10.0.11.5"
    port = 6380
    save_topology = false

  [output.file]

[interfaces]
device = "docker0"
type = "af_packet"
buffer_size_mb = 256
snaplen = 512

[protocols]
  [protocols.http]
  ports = [80, 8080, 8000, 5000, 8002]

[procs]
[agent]
[passwords]
```

For v1.0.0 Beta: packetbeat.yml
```
shipper:
 name:
interfaces:
 device: docker0
 type: af_packet
 buffer_size_mb: 256
 ##Tried with and without snaplen
 snaplen: 512
protocols:
  http:
    ports: [80, 8080, 8000, 5000, 8002]

  mysql:

  pgsql:
  redis:
  thrift:
output:
  elasticsearch:
    enabled: true
    host: 10.11.0.5
    port: 9200
    save_topology: false
  redis:
    enabled: false
    host: "10.11.0.5"
    port: 6380
    save_topology: false
```

Docker command:
```
docker run --net=host -d --name packetbeat --cpuset-cpus 8-15 -v /opt/packetbeat-docker:/etc/packetbeat packetbeat-agent packetbeat -e=true -v -c /etc/packetbeat/packetbeat.conf
```

FYI, the connection to these output services seems to be established. But transactions aren't published. 

Any pointers to where I am going wrong with this?
I know for a fact that no data is being sent because:
 a) the packetbeat list in redis was empty
 b) elasticsearch does not return any documents when I do 
```
user@10.11.0.5:~/packetbeat-perf-overhead$ curl -XGET 'http://localhost:9200/packetbeat-*/_search?pretty'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 0,
    "successful" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : 0.0,
    "hits" : [ ]
  }
}
```

c) tcpdump on port 9200 shows nothing but keepalive packets(length 0), while I am fetching 64kb files from nginx webserver

**Comment by rshriram** [comment] 2015-06-01 13:58
In case it helps, I captured the following debugging output using the -d '*' option.
```
main.go:144: DBG  Initializing output plugins
output_elasticsearch.go:58: INFO [ElasticsearchOutput] Using Elasticsearch http://10.11.0.5:9200
output_elasticsearch.go:59: INFO [ElasticsearchOutput] Using index pattern [packetbeat-]YYYY.MM.DD
output_elasticsearch.go:60: INFO [ElasticsearchOutput] Topology expires after 15s
publish.go:264: WARN No output is defined to store the topology. The server fields might not be filled.
publish.go:276: INFO No agent name configured, using hostname 'example.com'
geolite.go:49: WARN Couldn't load GeoIP database
main.go:157: DBG  Initializing protocol plugins
http.go:173: DBG  transactionsMap: 0xc2091942a0 http: 0xc20802cb58
tcp.go:222: DBG  Port map: map[8080:http 8000:http 5000:http 8002:http 3306:mysql 5432:pgsql 9090:thrift 80:http]
main.go:182: DBG  Initializing filters plugins
main.go:191: DBG  Filters plugins order: []
main.go:209: DBG  Initializing input plugins
main.go:213: DBG  Input plugin sniffer is enabled
sniffer.go:90: DBG  Sniffer type: af_packet devices: [docker0]
tcp.go:243: DBG  Layer type: Ethernet
main.go:266: DBG  Waiting for inputs to finish
sniffer.go:313: DBG  Packet number: 1
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:321: DBG  Ignore empty non-FIN packet
sniffer.go:313: DBG  Packet number: 2
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:321: DBG  Ignore empty non-FIN packet
sniffer.go:313: DBG  Packet number: 3
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:321: DBG  Ignore empty non-FIN packet
sniffer.go:313: DBG  Packet number: 4
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:123: DBG  Stream doesn't exists, creating new
tcp.go:138: DBG  pkt.start_seq=69154137 pkt.last_seq=69154302 stream.last_seq=0 (len=165)
http.go:516: DBG  Payload received: [GET /file_64k_1.txt HTTP/1.1
Host: 10.11.0.4
Accept: */*
Accept-Encoding: *
User-Agent: Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5
Connection: keep-alive

]
http.go:281: DBG  Stream state=0
http.go:331: DBG  HTTP Method=GET, RequestUri=/file_64k_1.txt
http.go:340: DBG  HTTP version 1.1
http.go:220: DBG  Data: Host: 10.11.0.4
Accept: */*
Accept-Encoding: *
User-Agent: Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5
Connection: keep-alive

http.go:221: DBG  Header: Host
http.go:231: DBG  HV:  10.11.0.4
http.go:237: DBG  Header: 'host' Value: '10.11.0.4'
http.go:220: DBG  Data: Accept: */*
Accept-Encoding: *
User-Agent: Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5
Connection: keep-alive

http.go:221: DBG  Header: Accept
http.go:231: DBG  HV:  */*
http.go:237: DBG  Header: 'accept' Value: '*/*'
http.go:220: DBG  Data: Accept-Encoding: *
User-Agent: Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5
Connection: keep-alive

http.go:221: DBG  Header: Accept-Encoding
http.go:231: DBG  HV:  *
http.go:237: DBG  Header: 'accept-encoding' Value: '*'
http.go:220: DBG  Data: User-Agent: Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5
Connection: keep-alive

http.go:221: DBG  Header: User-Agent
http.go:231: DBG  HV:  Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5
http.go:237: DBG  Header: 'user-agent' Value: 'Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5'
http.go:220: DBG  Data: Connection: keep-alive

http.go:221: DBG  Header: Connection
http.go:231: DBG  HV:  keep-alive
http.go:237: DBG  Header: 'connection' Value: 'keep-alive'
http.go:369: DBG  Empty content length, ignore body
http.go:635: DBG  transactionsMap 0xc2091942a0 http 0xc208030360
http.go:639: DBG  Received request with tuple: TcpTuple src[10.11.0.5:43927] dst[172.17.0.74:80] stream_id[1]
http.go:914: DBG  Parameters: 
sniffer.go:313: DBG  Packet number: 5
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:321: DBG  Ignore empty non-FIN packet
sniffer.go:313: DBG  Packet number: 6
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:138: DBG  pkt.start_seq=1889926450 pkt.last_seq=1889926692 stream.last_seq=0 (len=242)
http.go:516: DBG  Payload received: [HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Mon, 01 Jun 2015 13:15:55 GMT
Content-Type: text/plain
Content-Length: 65536
Last-Modified: Sun, 31 May 2015 16:09:45 GMT
Connection: keep-alive
ETag: "556b3249-10000"
Accept-Ranges: bytes

]
http.go:281: DBG  Stream state=0
http.go:193: DBG  parseResponseStatus: 200 OK
http.go:310: DBG  HTTP status_code=200, status_phrase=OK
http.go:340: DBG  HTTP version 1.1
http.go:220: DBG  Data: Server: nginx/1.8.0
Date: Mon, 01 Jun 2015 13:15:55 GMT
Content-Type: text/plain
Content-Length: 65536
Last-Modified: Sun, 31 May 2015 16:09:45 GMT
Connection: keep-alive
ETag: "556b3249-10000"
Accept-Ranges: bytes

http.go:221: DBG  Header: Server
http.go:231: DBG  HV:  nginx/1.8.0
http.go:237: DBG  Header: 'server' Value: 'nginx/1.8.0'
http.go:220: DBG  Data: Date: Mon, 01 Jun 2015 13:15:55 GMT
Content-Type: text/plain
Content-Length: 65536
Last-Modified: Sun, 31 May 2015 16:09:45 GMT
Connection: keep-alive
ETag: "556b3249-10000"
Accept-Ranges: bytes

http.go:221: DBG  Header: Date
http.go:231: DBG  HV:  Mon, 01 Jun 2015 13:15:55 GMT
http.go:237: DBG  Header: 'date' Value: 'Mon, 01 Jun 2015 13:15:55 GMT'
http.go:220: DBG  Data: Content-Type: text/plain
Content-Length: 65536
Last-Modified: Sun, 31 May 2015 16:09:45 GMT
Connection: keep-alive
ETag: "556b3249-10000"
Accept-Ranges: bytes

http.go:221: DBG  Header: Content-Type
http.go:231: DBG  HV:  text/plain
http.go:237: DBG  Header: 'content-type' Value: 'text/plain'
http.go:220: DBG  Data: Content-Length: 65536
Last-Modified: Sun, 31 May 2015 16:09:45 GMT
Connection: keep-alive
ETag: "556b3249-10000"
Accept-Ranges: bytes

http.go:221: DBG  Header: Content-Length
http.go:231: DBG  HV:  65536
http.go:237: DBG  Header: 'content-length' Value: '65536'
http.go:220: DBG  Data: Last-Modified: Sun, 31 May 2015 16:09:45 GMT
Connection: keep-alive
ETag: "556b3249-10000"
Accept-Ranges: bytes

http.go:221: DBG  Header: Last-Modified
http.go:231: DBG  HV:  Sun, 31 May 2015 16:09:45 GMT
http.go:237: DBG  Header: 'last-modified' Value: 'Sun, 31 May 2015 16:09:45 GMT'
http.go:220: DBG  Data: Connection: keep-alive
ETag: "556b3249-10000"
Accept-Ranges: bytes

http.go:221: DBG  Header: Connection
http.go:231: DBG  HV:  keep-alive
http.go:237: DBG  Header: 'connection' Value: 'keep-alive'
http.go:220: DBG  Data: ETag: "556b3249-10000"
Accept-Ranges: bytes

http.go:221: DBG  Header: ETag
http.go:231: DBG  HV:  "556b3249-10000"
http.go:237: DBG  Header: 'etag' Value: '"556b3249-10000"'
http.go:220: DBG  Data: Accept-Ranges: bytes

http.go:221: DBG  Header: Accept-Ranges
http.go:231: DBG  HV:  bytes
http.go:237: DBG  Header: 'accept-ranges' Value: 'bytes'
http.go:374: DBG  Read body
sniffer.go:313: DBG  Packet number: 7
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:138: DBG  pkt.start_seq=1889926692 pkt.last_seq=1889927138 stream.last_seq=1889926692 (len=446)
http.go:516: DBG  Payload received: [<SNIP>]
http.go:281: DBG  Stream state=3
http.go:389: DBG  eat body: 242
http.go:404: DBG  bodyReceived: 446
sniffer.go:313: DBG  Packet number: 8
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:321: DBG  Ignore empty non-FIN packet
sniffer.go:313: DBG  Packet number: 9
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:321: DBG  Ignore empty non-FIN packet
sniffer.go:313: DBG  Packet number: 10
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:138: DBG  pkt.start_seq=1889939724 pkt.last_seq=1889940170 stream.last_seq=1889927138 (len=446)
tcp.go:151: DBG  Gap in tcp stream. last_seq: 1889927138, seq: 1889939724
tcp.go:94: DBG  Tcp stream expired
```

**Comment by rshriram** [comment] 2015-06-01 14:35
Just an update:
 Strangely, when i fetch a small index.html file or a 1Kb file, publishing works. Looking at the log statements above, it seems for small files, the transactions are completed.
```
sniffer.go:313: DBG  Packet number: 100
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:321: DBG  Ignore empty non-FIN packet
sniffer.go:313: DBG  Packet number: 101
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:138: DBG  pkt.start_seq=687711063 pkt.last_seq=687711063 stream.last_seq=687711063 (len=0)
sniffer.go:313: DBG  Packet number: 102
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:138: DBG  pkt.start_seq=1389422105 pkt.last_seq=1389422105 stream.last_seq=1389421525 (len=0)
http.go:591: DBG  Publish something on connection FIN
http.go:710: DBG  Received response with tuple: TcpTuple src[10.11.0.5:43955] dst[172.17.0.74:80] stream_id[12]
http.go:757: DBG  HTTP transaction completed: map[code:%!s(uint16=200) content_length:%!s(int=1026) phrase:OK]
sniffer.go:313: DBG  Packet number: 103
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:321: DBG  Ignore empty non-FIN packet
output_elasticsearch.go:150: DBG  Publish event
```
[this fits entirely inside one packet]

When i move up to larger sizes (4kb, 64kb, etc), I get the same behavior as above. For example, I tried with this file:
https://raw.githubusercontent.com/twbs/bootstrap/master/docs/assets/js/vendor/jszip.min.js
No events were published. The stream assembly seems to be broken and new streams continue to be created.
```
sniffer.go:313: DBG  Packet number: 116
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:321: DBG  Ignore empty non-FIN packet
sniffer.go:313: DBG  Packet number: 117
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:138: DBG  pkt.start_seq=3390985470 pkt.last_seq=3390985916 stream.last_seq=3390972884 (len=446)
tcp.go:151: DBG  Gap in tcp stream. last_seq: 3390972884, seq: 3390985470
tcp.go:94: DBG  Tcp stream expired
sniffer.go:313: DBG  Packet number: 118
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:123: DBG  Stream doesn't exists, creating new
tcp.go:138: DBG  pkt.start_seq=3390999950 pkt.last_seq=3391000396 stream.last_seq=0 (len=446)
..SNIP...
sniffer.go:313: DBG  Packet number: 123
tcp.go:288: DBG  IPv4 packet
tcp.go:302: DBG  TCP packet
tcp.go:123: DBG  Stream doesn't exists, creating new
...SNIP...
tcp.go:138: DBG  pkt.start_seq=3391037975 pkt.last_seq=3391037975 stream.last_seq=3391029356 (len=0)
http.go:591: DBG  Publish something on connection FIN
http.go:710: DBG  Received response with tuple: TcpTuple src[172.17.0.74:80] dst[10.11.0.5:43958] stream_id[15]
http.go:714: WARN Response from unknown transaction. Ignoring: TcpTuple src[172.17.0.74:80] dst[10.11.0.5:43958] stream_id[15]
```
which clearly indicates that part of the connection context (http request) is lost.

**Comment by tsg** [comment] 2015-06-02 16:02
Interesting, it seems that the streams expire. We'll have a look and report back.

**Comment by rshriram** [comment] 2015-06-04 13:44
Any updates?

**Comment by tsg** [comment] 2015-06-04 14:10
Not yet, I hope to manage to have a look at it today or tomorrow.

**Comment by tsg** [comment] 2015-06-04 20:46
Oh, I think I get it. The `docker0` interface probably has a large MTU size but the `snaplen` (i.e. the max we capture per packet) it's set to either 512 or 1514 in your case.

We try to be smart about it and set the `snaplen` size to 16436 (max value possible for a packet) if the interface is "any" or a loopback interface. But if it's not, we use the ethernet default of 1514.

It's probably better to read the MTU size and set it based on that. Anyway, easiest way to test this out would be a configuration like:
<pre>
interfaces:
 device: docker0
 type: af_packet
 buffer_size_mb: 256
 snaplen: 16436
</pre>

This seems to make it work in my tests at least.

**Comment by rshriram** [comment] 2015-06-04 23:14
Thats strange. ifconfig docker0 shows MTU to be 1500

**Comment by rshriram** [comment] 2015-06-04 23:37
In my case, setting snaplen to 65536 seems to take make things work partially. I still see the stream expired messages in the logs. Also, there is a loss of fidelity in the data published to redis:
```
10.11.0.5:6380> LINDEX packetbeat 27019
"{\"client_ip\":\"10.11.0.5\",\"client_port\":51789,\"client_proc\":\"\",\"client_server\":\"\",\"count\":1,\"http\":{\"code\":0,\"content_length\":0,\"phrase\":\"\"},\"ip\":\"172.17.0.74\",\"method\":\"GET\",\"params\":\"\",\"path\":\"/file_64k_2.txt\",\"port\":80,\"proc\":\"\",\"query\":\"GET /file_64k_2.txt\",\"responsetime\":0,\"server\":\"\",\"shipper\":\"host1\",\"status\":\"OK\",\"timestamp\":\"2015-06-04T23:30:00.995Z\",\"type\":\"http\"}"
10.11.0.5:6380> LINDEX packetbeat 27018
"{\"client_ip\":\"10.11.0.5\",\"client_port\":51759,\"client_proc\":\"\",\"client_server\":\"\",\"count\":1,\"http\":{\"code\":0,\"content_length\":0,\"phrase\":\"\"},\"ip\":\"172.17.0.74\",\"method\":\"GET\",\"params\":\"\",\"path\":\"/file_64k_2.txt\",\"port\":80,\"proc\":\"\",\"query\":\"GET /file_64k_2.txt\",\"responsetime\":0,\"server\":\"\",\"shipper\":\"host1\",\"status\":\"OK\",\"timestamp\":\"2015-06-04T23:30:00.985Z\",\"type\":\"http\"}"
10.11.0.5:6380> LINDEX packetbeat 27017
"{\"client_ip\":\"10.11.0.5\",\"client_port\":51797,\"client_proc\":\"\",\"client_server\":\"\",\"count\":1,\"http\":{\"code\":200,\"content_length\":65538,\"phrase\":\"OK\"},\"ip\":\"172.17.0.74\",\"method\":\"GET\",\"params\":\"\",\"path\":\"/file_64k_2.txt\",\"port\":80,\"proc\":\"\",\"query\":\"GET /file_64k_2.txt\",\"responsetime\":0,\"server\":\"\",\"shipper\":\"host1\",\"status\":\"OK\",\"timestamp\":\"2015-06-04T23:30:01.000Z\",\"type\":\"http\"}"
```

**Comment by rshriram** [comment] 2015-06-04 23:43
With regard to the snaplen issue, is it possible to work with frames that are not MTU sized? Expecting full sized frames to be captured off the wire (pcap/afpacket) increases cpu usage a lot due to memcpy (whether its 1500 bytes or 64K). I realize that this may not work with all protocols but it could certainly work with HTTP, where the http parser can communicate to the tcp layer that it can skip N bytes (where N is content-length) or not worry about gaps in streams when its still parsing the HTTP body.

I agree that this might reduce the fidelity of captured data but it comes at the cost of lower cpu usage.

I was fiddling with the code and found that the TCP parser discards streams when there are gaps. I disabled that piece of code and was able to make packetbeat recognize the 64kb file fetch, and publish the http transaction to redis, by using snaplen of 512 bytes. However, the nature of the http state machine in packetbeat is such that, this hack works only for connections containing a single request/response.  With HTTP keepalives, the http parsing code ends up recognizing only one transaction for the entire connection even when there were 500 actually.

**Comment by tsg** [comment] 2015-06-05 08:27
> In my case, setting snaplen to 65536 seems to take make things work partially. I still see the stream expired messages in the logs. Also, there is a loss of fidelity in the data published to redis:

When you say there's a loss in fidelity when using the 65k snaplen, what do you refer to?

>  I was fiddling with the code and found that the TCP parser discards streams when there are gaps.

The point of dropping the stream when gaps are encountered is that we will later try to recognise the stream with new packets. It's likely that the next request within the same stream will be at the boundary of the packets, so we can reattach there in case of problems. That said, gaps should only happen in exceptional cases, if they happen with every request this won't work too well.

> I disabled that piece of code and was able to make packetbeat recognize the 64kb file fetch, and publish the http transaction to redis, by using snaplen of 512 bytes.

Do you have concrete data for the difference in CPU time between 512 bytes vs 1500 bytes snaplen? In my experience that doesn't change that much. 

65k might be a different story, but the copy is still made for the size of the packet, not the full snaplen. For af_packet, it does mean a significantly lower number of packets per MB of data, but otoh there will be generally fewer packets on the wire as well.

**Comment by rshriram** [comment] 2015-06-09 20:43
On Fri, Jun 5, 2015 at 4:27 AM, Tudor Golubenco <notifications@github.com>
wrote:
>>
>> In my case, setting snaplen to 65536 seems to take make things work
partially. I still see the stream expired messages in the logs. Also, there
is a loss of fidelity in the data published to redis:
>
> When you say there's a loss in fidelity when using the 65k snaplen, what
do you refer to?

I see entries in redis, where the content-length is 0 (even though the
response is 64Kb in size ). And what I don't understand is why the docker0
interface shows MTU of 1500 when I do ifconfig, yet a snaplen of 1512 bytes
doesn't suffice.

>>
>> I was fiddling with the code and found that the TCP parser discards
streams when there are gaps.
>
> The point of dropping the stream when gaps are encountered is that we
will later try to recognise the stream with new packets. It's likely that
the next request within the same stream will be at the boundary of the
packets, so we can reattach there in case of problems. That said, gaps
should only happen in exceptional cases, if they happen with every request
this won't work too well.

So, thats what seemed to be happening with the default snaplen. If I
increase the snaplen from 512 to 64K, then I am wasting a lot of CPU to
decode the packets.

>>
>> I disabled that piece of code and was able to make packetbeat recognize
the 64kb file fetch, and publish the http transaction to redis, by using
snaplen of 512 bytes.
>
> Do you have concrete data for the difference in CPU time between 512
bytes vs 1500 bytes snaplen? In my experience that doesn't change that much.

Not between 512 and 1500. Its between 512 and 64K snaplen.

>
> 65k might be a different story, but the copy is still made for the size
of the packet, not the full snaplen. For af_packet, it does mean a
significantly lower number of packets per MB of data, but otoh there will
be generally fewer packets on the wire as well.
>

True, but judging by the CPU increase, it seems the packets are pretty
large. I need to double check the numbers.

Could the hardware segmentation offload be creating these issues?

**Comment by tsg** [comment] 2015-06-11 10:32
> I see entries in redis, where the content-length is 0 (even though the
response is 64Kb in size ). 

Hmm, I see. This result I'm not able to reproduce at the moment. Can you give me some details about how you test (what web server, what command for the download).

> And what I don't understand is why the docker0
interface shows MTU of 1500 when I do ifconfig, yet a snaplen of 1512 bytes
doesn't suffice.

After reading a bit more, it seems that the MTU is ignored by virtual devices. We can expect packets of any length up to 65535. We'll reflect this in default settings for packetbeat. Until then, I recommend running with `snaplen = 65535`. 

We'll also try to make the parser be able to jump over missing data from the response, but this will be best effort anyway.

**Comment by tsg** [comment] 2015-06-12 17:53
Changed the default for the snaplen to 65535 in #155. I leave this ticket open for now, to clarify:

* the issue with the content length being zero
* make the http parser more robust against partial packet loss.

**Comment by Rafff** [comment] 2015-06-19 17:38
It seems that I have the same problem rshriram has.

I am trying to log requests passing between nginx and varnish, all this into Docker.
When requesting for an endpoint with tiny body, the transaction is published to redis. And when the body is bigger, it looks that packetbeat lose the end of the packet :
```
http.go:253: DBG  Header: 'content-length' Value: '26550'
```
(26550 being the real length of my response body)
and a few lines later :
```
http.go:390: DBG  Read body
http.go:405: DBG  eat body: 327
http.go:420: DBG  bodyReceived: 16043
```

Here is my packetbeat config:

```
shipper:
 name: nginx1
 ignore_outgoing: true

interfaces:
 device: lo

protocols:
  http:
    ports: [6081]
    type: af_packet
    buffer_size_mb: 512
    snaplen: 65535

output:
  redis:
   enabled: true
   host: 172.17.42.1
   port: 6379
   save_topology: true
```
(I tried to change `buffer_size_mb` and `snaplen` values, it doesn't help my issue)

Let me know if I can help more by provinding traces/logs/whatever.
I hope this issue will fix my problem (it's the same issue, right ?)

**Comment by rshriram** [comment] 2015-06-19 18:48
@tsg clarifications:
 I think the content length being zero was because I had hacked up the code to accept gaps in streams, but didn't properly fix the rest of the code. As a consequence, packetbeat was publishing transactions to redis, but there was no response time nor response length. I thought the response length can be obtained from the HTTP content-length field, such that even if there are holes in the stream, you can skip them, as long as the hole is in the right tcp sequence number range, i.e., (seqno_at_start_of_body - seq_no_end_of_body). So content length can still be logged, under the assumption that the packetbeat missed the packets (independent of whether the packets actually went through or not).

Partial packet loss -- that was a typo on my end. I meant partial loss of HTTP body content.

Now, the above technique of ignoring holes in http streams raises two corner cases that need to be handled (it may already be there in the code base and I might just be missing them):

1. recording response time: even if there is a gap in the stream, if packetbeat sees the end of the HTTP response body, it needs to log the response time for the transaction.
 End of HTTP response body can be detected by matching the actual sequence numbers against the expected sequence number in the ideal scenario.

2. when to publishing the transaction: In a http connection with keepalive==true, if packetbeat detects end of a HTTP response (by detecting that the sequence numbers have crossed the expected sequence number), does it publish the transaction immediately?
And then syncs up to the next transaction if the packet contains a HTTP request.

I haven't tested the code since the last time I posted the bug report. So I don't know if the above cases are handled already or not. If not, then they need to be handled, in order to be resilient to holes in the packet stream.

**Comment by tsg** [comment] 2015-06-19 19:03
@Rafff there is a problem with your configuration, the sniffer settings should go under the interface section:

<pre>
shipper:
 name: nginx1
 ignore_outgoing: true

interfaces:
 device: lo
 type: af_packet
 buffer_size_mb: 512
 snaplen: 65535

protocols:
  http:
    ports: [6081]

output:
  redis:
   enabled: true
   host: 172.17.42.1
   port: 6379
   save_topology: true
</pre>

Can you try it like that? I'd be surprised if you have packet loss with such a large buffer.

**Comment by tsg** [comment] 2015-06-19 19:08
@rshriram Thanks for the details, I was just working on this pull #169 (not yet merged) for tolerating some packet loss. 

The two points you raised should be addressed because we're using sequence numbers to know how much of the body we received.

**Comment by Rafff** [comment] 2015-06-22 09:39
Oh, right ! Thanks @tsg, it works for me now

**Comment by tsg** [comment] 2015-08-03 07:48
Closing this one as it should be fixed with beta2. If there's still something that seems wrong, please open a new ticket.

**Closed by tsg** 2015-08-03 07:48 UTC
Labels: bug, needs details
