### ISSUE TITLE
Packetbeat Process Dying for Some Agents and Not Others

### ISSUE THREAD

**Issue by bootbeast** [elastic/packetbeat#115] opened 2015-04-09 22:29 UTC
Greetings,

I've got a pretty straightforward instance of Packetbeat/Elasticsearch/Kibana running and I'm having a problem with some of the agents whose daemon's won't stay running.  Nothing is blocking network connectivity between server and agents and I have applied the template detailed in issue #107. 

Here is what I get in the syslog within a few minutes of starting the service. 
Apr  9 21:55:05 web-prod-01 /usr/bin/packetbeat[13361]: output_elasticsearch.go:105: Fail to publish IP addresses: 2015-04-09 21:55:05.960053171 +0000 UTC: Error [UnavailableShardsException[[packetbeat-topology][1] Primary shard is not active or isn't assigned is a known node. Timeout: [1m], request: index {[packetbeat-topology][server-ip][web-prod-01], source[{"Name":"web-prod-01","IPs":"192.168.2.50,fe80::4fe:85ff:fea4:8b9b"}]}]] Status [503] [503]
Apr  9 21:55:05 web-prod-01 /usr/bin/packetbeat[13361]: publish.go:363: Failed to publish topology: 2015-04-09 21:55:05.960053171 +0000 UTC: Error [UnavailableShardsException[[packetbeat-topology][1] Primary shard is not active or isn't assigned is a known node. Timeout: [1m], request: index {[packetbeat-topology][server-ip][web-prod-01], source[{"Name":"web-prod-01","IPs":"192.168.2.50,fe80::4fe:85ff:fea4:8b9b"}]}]] Status [503] [503]
Apr  9 21:55:05 web-prod-01 /usr/bin/packetbeat[13361]: main.go:223: 2015-04-09 21:55:05.960053171 +0000 UTC: Error [UnavailableShardsException[[packetbeat-topology][1] Primary shard is not active or isn't assigned is a known node. Timeout: [1m], request: index {[packetbeat-topology][server-ip][web-prod-01], source[{"Name":"web-prod-01","IPs":"192.168.2.50,fe80::4fe:85ff:fea4:8b9b"}]}]] Status [503] [503]

How can I remedy this problem?

**Comment by bootbeast** [comment] 2015-04-10 18:44
When the problem started, yes, low free disk space was a problem on the Packetbeat server.  But I've increased storage and it's now 60% free. All the agents have plenty of system resources too.    When I added storage, the agents running on Windows as services reconnected with no action, but 4 of the 6 Linux hosts (which are clones of each other from the same AWS AMI) are still giving this error and the Packetbeat service dies.

**Comment by tsg** [comment] 2015-04-15 17:55
Can you try deleting the packetbeat-topology index? It's only used for temporary data, so dropping it once shouldn't be a problem:

    curl -XDELETE http://<elasticsearch-url>/packetbeat-topology

**Comment by tsg** [comment] 2015-05-28 08:27
Closing this one because we would need more data. In the future, we'd prefer you open an issue on the new [forums](https://discuss.elastic.co/c/beats/packetbeat) we have for Packetbeat or on the #beats channel on Freenode.

We're trying to keep GitHub only for confirmed bugs and enhancements requests.

**Closed by tsg** 2015-05-28 08:27 UTC
Labels: question
